#ifndef ROSE_TINTED_VERSION_H
#define ROSE_TINTED_VERSION_H

#define RT_VERSION_MAJOR "0"
#define RT_VERSION_MINOR "0"
#define RT_VERSION_PATCH "0"
#define ROSE_TINTED_VERSION_FULL \
    RT_VERSION_MAJOR "." RT_VERSION_MINOR "." RT_VERSION_PATCH

#endif // ROSE_TINTED_VERSION_H
