project(RoseTinted)

set(ROSE_TINTED_SOURCES
    src/system/dedicated_main.cpp
    src/gui/gui_globals.cpp
    src/gui/imgui_implementor.cpp
    src/gui/imgui_debugger.cpp
    src/gui/imgui_main_menu.cpp
    src/app/rose_tinted.cpp
    src/things/player.cpp
    src/things/collision_tester_3d.cpp
    src/thirdparty/getargs/argument.cpp
    src/thirdparty/getargs/argument_parser.cpp
    src/thirdparty/DearImGui/imgui.cpp
    src/thirdparty/DearImGui/imgui_demo.cpp
    src/thirdparty/DearImGui/imgui_draw.cpp
    src/thirdparty/DearImGui/imgui_freetype.cpp
    src/thirdparty/DearImGui/imgui_impl_glfw.cpp
    src/thirdparty/DearImGui/imgui_impl_opengl3.cpp
    src/thirdparty/DearImGui/imgui_stdlib.cpp
    src/thirdparty/DearImGui/imgui_tables.cpp
    src/thirdparty/DearImGui/imgui_widgets.cpp)
